version: "3.8"
services:
  couchdb1:
    image: couchdb:3.1.0
    restart: always
    ports:
      - 5984:5984
    environment:
      - NODENAME=10.0.0.10
      - ERL_FLAGS=-setcookie monster
    volumes:
      - ./config/couchdb:/opt/couchdb/etc/local.d
      - ./data/couchdb/1:/opt/couchdb/data
    networks:
      couchdb-net:
        ipv4_address: 10.0.0.10
  clouseau1:
    build: .
    restart: always
    depends_on:
      - couchdb1
    volumes:
      - ./data/clouseau/1:/data
    network_mode: service:couchdb1
networks:
  couchdb-net:
    name: couchdb-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
caproverOneClickApp:
    variables:
        - id: $$cap_couchdb_version
          label: CouchDB Version Tag
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/library/couchdb/tags/
          defaultValue: '3'
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_couchdb_user
          label: CouchDB Username
          defaultValue: mainuser
          validRegex: /^([a-zA-Z0-9_])+$/
        - id: $$cap_couchdb_password
          label: CouchDB Password
          defaultValue: ''
          validRegex: /.{1,}/
    instructions:
        start: >-
            CouchDB is a database that uses JSON for documents, an HTTP API, & JavaScript/declarative indexing.
            After installation on CapRover, it will be available as srv-captain--YOUR_CONTAINER_NAME at port 5984 to other CapRover apps.
            Enter your CouchDB Configuration parameters and click on next. It will take about a minute for the process to finish.
        end: CouchDB is deployed and available as $$cap_appname at port 5984 to other apps
    displayName: CouchDB
    isOfficial: true
    description: Apache CouchDB is an open-source document-oriented NoSQL database, implemented in Erlang
    documentation: Taken from https://hub.docker.com/_/couchdb/
